### ISSUE TITLE
Task#4 Clause#6

### ISSUE THREAD

**Issue by klakhov** [SemyonBevzuk/Programming_practice_381908-1-2#36]
Если привязать к задаче бд по типу SQLite то можно ли нивелировать пункт 
> Фильмы хранятся упорядоченно по названию и годам ?

Просто добывание оттуда строк не  будет зависеть от порядка их хранения, а если очень нужно будет, всегда есть ORDER BY
К тому же, кажется по ходу задачи этот момент никак не используется

И еще вопрос, меню для выбора это консольная штука или можно графику какую-нибудь подключать?

**Comment by SemyonBevzuk** [comment]
Использование БД будет плюсом.

Достаточно консольного меню.

**Comment by klakhov** [comment]
Хорошо, спасибо.
Но все таки, если зарекаться на графику, подскажите какую-нибудь библиотеку для окон с controls, которую можно быстро изучить)

**Comment by SemyonBevzuk** [comment]
Уф, ну вот с быстренько это задача сложная...

В студии можно быстро сверстать через CLR и Windows Form. Это как в C#, создаёте графически форму, вешаете функции на события и готово. 

В Clion можно попробовать подключить Qt, в нём есть QtDesigner для графического редактирования интерфейса. Идея аналогичная.

**Comment by klakhov** [comment]
Спасибо! Попробую. Если уж тяжко пойдет, консоль нам в помощь =)
