### ISSUE TITLE
Задание 4 № 6

### ISSUE THREAD

**Issue by KimNikita** [SemyonBevzuk/Programming_practice_381908-1-2#41]
Перегрузка операторов уже не нужна?

**Comment by SemyonBevzuk** [comment]
Зависит от контекста операции. 
Перегрузить =, логические операции можно.
Можно организовать выдачу нужного фильма по названию через [].
Оператор + уже под вопросом, он уже менее интуитивен в данном контексте, по моему мнению, лучше реализовать методы с понятными именами.
