### ISSUE TITLE
Task 6, battleship

### ISSUE THREAD

**Issue by leolnid** [SemyonBevzuk/Programming_practice_381908-1-2#43]
Добрый день! Появиласт дея сделать это в формате нормального проекта. Сделать сайт - приложение, бекенд на с++, фронт на js + vue(Скорее всего). Вопрос, можно ли объединиться с Кириллом в пару и выполнить задачу в таком виде?

**Comment by SemyonBevzuk** [comment]
Добрый день!
Хм, весьма занимательная идея. Но я не знаю как вы это сделаете :D 
В плане насколько удобные средства существуют для интеграции js и с++?
