### ISSUE TITLE
Задание 4 №6

### ISSUE THREAD

**Issue by KimNikita** [SemyonBevzuk/Programming_practice_381908-1-2#44]
![1](https://user-images.githubusercontent.com/60927460/78021903-b4756780-735c-11ea-88b2-05853e8abf10.jpg)
![2](https://user-images.githubusercontent.com/60927460/78021905-b5a69480-735c-11ea-88ff-53c7c12eda07.jpg)
![3](https://user-images.githubusercontent.com/60927460/78021907-b63f2b00-735c-11ea-8679-732f19b3bc95.jpg)
русские символы не читает

**Comment by SemyonBevzuk** [comment]
Скорее всего это проблема наблюдается в Windows, я не смог её воспроизвести у себя.
Попробуйте задать кодировку консоли через функции из windows.h:
```
SetConsoleCP(1251);
SetConsoleOutputCP(1251);
```
